name: Release

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      version:
        description: Select version to publish
        options:
          - patch
          - minor
          - major
        required: true
        type: choice

jobs:
  release:
    name: Release Package to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-workflow

      - name: Set Git User Config Details
        run: |
          git config --global user.email "liam@liam.codes"
          git config --global user.name "Liam Howell"

      - name: Bump Package Version & Generate Changelog
        run: |
          cd ./packages/tailwind-compose
          yarn version --${{ github.event.inputs.version }}
          yarn changelog

      - name: Push Version Update & Tags
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./packages/tailwind-compose
          VERSION=$(node -p -e "require('./package.json').version")
          git add CHANGELOG.md && git commit -m "docs: update v$VERSION changelog"
          git push
          git push --tags

      - name: Publish Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ./packages/tailwind-compose
          cp ../../README.md ./README.md
          cp ../../LICENSE.md ./LICENSE.md
          yarn publish --non-interactive
