name: Test Code

on:
  pull_request:

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-workflow

      - name: Test Code
        run: |
          yarn workspace tailwind-compose test

      - name: Publish To Coveralls
        uses: coverallsapp/github-action@master
        with:
          base-path: ./packages/tailwind-compose
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/tailwind-compose/coverage/lcov.info
