name: Verify Code Standard

on:
  push:

jobs:
  verify:
    name: Verify Code Standard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-workflow

      - name: Build
        run: |
          yarn workspace tailwind-compose clean
          yarn workspace tailwind-compose build

      - name: Verify Code Standard
        run: |
          yarn workspace tailwind-compose format
          yarn workspace tailwind-compose lint
          yarn workspace tailwind-compose typescript:verify
